# Generated by Django 4.1.3 on 2022-12-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
