# Generated by Django 4.1.3 on 2022-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='emotion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
