# Generated by Django 4.1.3 on 2022-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='emotion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
