# Generated by Django 4.1.3 on 2022-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
